gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# API
from rest_framework import routers
from src.core import views
from src.funcionario.api.views import FuncionarioViewSet
from src.registro_hora_extra.api.views import RegistroHoraExtraViewSet

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/banco-horas', RegistroHoraExtraViewSet)
#

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.core.urls')),
    path('funcionario/', include('src.funcionario.urls')),
    path('horas-extras/', include('src.registro_hora_extra.urls')),
    path('departamento/', include('src.departamento.urls')),
    path('documento/', include('src.documentos.urls')),
    path('empresa/', include('src.empresa.urls')),
    path("accounts/", include("django.contrib.auth.urls")),

    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/funcionario/urls.py
from django.urls import path
from .views import ListFuncionario, EditFuncionario, DeleteFuncionario, FuncionarioNovo
from . views import pdf_reportlab, Pdf

urlpatterns = [
    path('', ListFuncionario.as_view(), name='list_funcionario'),
    path('novo/', FuncionarioNovo.as_view(), name='create_funcionario'),
    path('editar/<int:pk>/', EditFuncionario.as_view(), name='update_funcionario'),
    path('deletar/<int:pk>/', DeleteFuncionario.as_view(), name='delete_funcionario'),
    path('pdf-reportlab', pdf_reportlab, name='pdf_reportlab'),
    path('relatorio_funcionarios_html', Pdf.as_view(), name='relatorio_funcionarios_html'),

]

src/documentos/models.py
from django.db import models
from django.urls import reverse

from src.funcionario.models import Funcionario


class Documentos(models.Model):
    descricao = models.CharField(max_length=70)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

src/funcionario/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

from src.departamento.models import Departamento
from src.empresa.models import Empresa
from django.urls import reverse


class Funcionario(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    nome = models.CharField(max_length=100)
    departamento = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)
    de_ferias = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('list_funcionario')

# somar as horas extras do funcionario logado. o Filter faz faz as horas utilizadas a nao serem contabilizadas
    @property
    def total_hora_extra(self):
        total = self.registrohoraextra_set.filter(utilizada=False).aggregate(Sum('horas'))['horas__sum']
        return total or 0

    def __str__(self):
        return self.nome

src/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from src.funcionario.models import Funcionario


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.funcionario.id])

    def __str__(self):
        return self.motivo

src/funcionario/api/views.py
from rest_framework import viewsets
from src.funcionario.api.serializers import FuncionarioSerializers
from src.funcionario.models import Funcionario
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication


class FuncionarioViewSet(viewsets.ModelViewSet):
    queryset = Funcionario.objects.all()
    serializer_class = FuncionarioSerializers
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

src/funcionario/views.py
import io

from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from reportlab.pdfgen import canvas

from . models import Funcionario

# PDF via Html.

# Usar pare fazer o carregamento do template
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa


class ListFuncionario(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class EditFuncionario(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamento']


class DeleteFuncionario(DeleteView):
    model = Funcionario

    def get_success_url(self):
        return reverse_lazy('list_funcionario')


class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamento']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)


def pdf_reportlab(request):
    # constroe a requisicao
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=" mypdf.pdf"'
    #               ||          Faz baixar o arquivo (download) ao invés de abrir em nova aba ou janela

    # constroe o arquivo
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)

    p.drawString(10, 810, 'Hello, World!')

    palavras = ['palavra 1', 'palavra 2', 'palavra 3']

    y = 790
    for palavra in palavras:
        p.drawString(10, y , palavra)
        y -= 40

    # injeta o arquivo dentro da response
    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    # e envia a response
    return response


# Classe criada para criacao de relatorio. Assim nao precisa sempre repetir
# a escrita do codigo abaixo
class Render:
    # com staticmethod nao eh preciso instanciar um objeto render para utilizar
    @staticmethod
    # render vai receber o path do template, os parametros que euq euro contextualizar e o nore do arquivo.
    def render(path: str, params: dict, filename: str):
        # 1o. carrega o template, depois renderizo o html utilizando os parametros(variaveis, querysets, listas, dicionarios)
        # crio a response, cria o objeto pdf com encode UTF8, e passo a response como parametro. O objeto pdf vai conter o
        # objeto pdf em si que eu quero estar renderizando
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            # Se nao constar nenhum erro, iniciar a response. Cria o Httpreponse, faz o getvalues, seto o content type para pdf
            # e no percent s (% s) passo o nome do relatorio
            response = HttpResponse(
                response.getvalue(), content_type="application/pdf")
            response['Content-Disposition'] = 'attachment;filename=%s.pdf' % filename
            return response
        else:
            return HttpResponse("Error rendering PDF", status=400)


class Pdf(View):
    # Essa def vai responder o metodo get. Criar a lista de parametros(pode passar variaveis, querysets, requests.
    #
    def get(self, request):
        params = {
            'today': 'Variavel today',
            'sales': 'Variavel sales',
            'request': request,
        }
        return Render.render('funcionario/relatorio.html', params, 'myfile')
        # retorno o moetodo render(staticmethod) e passar o tejmplate que voce
        # quer renderizar.
        # Criar o arquivo relatorio .html em funcionarios

src/funcionario/templates/funcionario/funcionario.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Deu certo</h1>
</body>
</html>

src/funcionario/templates/funcionario/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}

    Edit

    <form method="post">

        {% csrf_token %}

        {{ form }}
        <h1>Tem certeza que voce deseja deletar? {{ object }}</h1>

        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
{% endblock %}

src/funcionario/templates/funcionario/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}


{% block main %}
{{ object }}
<form method="post">

    {% csrf_token %}

    {{ form|bootstrap }}
<br>
    <button type="submit">Salvar</button>
</form>

<a href="{% url 'create_documento'  %}" class="btn btn-primary">Novo Documento</a>

<br>
<h2>Documentos</h2>
<ul>
{% for documento in object.documentos_set.all %}
    <li>
        <a href="#">
            {{ documento }}
        </a>

    </li>
{% endfor %}
</ul>
<br>

<br>

<br>
<h2>Banco de Horas</h2>
<br>
<ul>
{% for registro_hora in object.registrohoraextra_set.all %}
    <li>
        <a href="{% url 'update_hora_extra' registro_hora.id %}">
            {{ registro_hora.motivo }} | {{ registro_hora.horas }}
        </a>

    </li>
{% endfor %}
</ul>
<!--@property em models - resultado da soma de horas extras definidos no models(funcionario)-->
<h3>Total de horas extra: {{ object.total_hora_extra }}</h3>

{% endblock %}

src/funcionario/templates/funcionario/funcionario_list.html
{% extends 'base.html' %}
{% block main %}

    List
    {% for funcionario in object_list %}
        <br>
        <a href="{% url 'update_funcionario' funcionario.id %}">
            {{ funcionario }}
        </a>
        <a href="{% url 'delete_funcionario' funcionario.id %}">
            Deletar</a>

    {% endfor%}
<br>
<a href="{% url 'create_funcionario' %}" class="btn btn-info">Novo</a>
<a href="{% url 'pdf_reportlab' %}" class="btn btn-success">Relatorio PDF</a>
<a href="{% url 'relatorio_funcionarios_html' %}" class="btn btn-success">Relatorio Html</a>



{% endblock%}

src/funcionario/templates/funcionario/funcionario_update_form.html
{% extends 'base.html' %}

{% block main %}
    <form method="post">

        {% csrf_token %}

        {{ form }}

        <button type="submit">Salvar</button>
    </form>
{% endblock %}

src/funcionario/templates/funcionario/relatorio.html
{% extends 'base.html' %}

{% block main %}
    <h1>Meu Relatorio</h1>
    <h2> {{ sales }}</h2>
{% endblock %}